include "base-config.conf"

kafka {
  input.topic = ${job.env}".generate.certificate.request"
  output.failed.topic = ${job.env}".generate.certificate.failed"
  output.duplicate.topic = ${job.env}".generate.certificate.duplicate"
  output.unique.topic = ${job.env}".generate.certificate.unique"
  groupId = ${job.env}".certificate-dedup-group"
}

task {
  consumer.parallelism = 4
  parallelism = 4
  checkpoint.interval.ms = 60000
  state.backend = "rocksdb"
  state.ttl.time = 86400000  # 24 hours in ms
}

clickhouse {
  url = "jdbc:clickhouse://https:localhost:8123/warehouse"
  username = "pyspark"
  password = "PySp@r712"
  batch.size = 20

  # Database tables
  table{
    certificates = "certificates"
  }}

deduplication {
  key.field = "certificate_id"
  # Optional: composite keys (comma-separated)
  # key.fields = "certificate_id,user_id"

  # State backend storage
  state.ttl.seconds = 86400  # 24 hours

  # Batch insert settings
  batch.size = 1000
  batch.timeout.ms = 5000
}

task {
  consumer.parallelism = 1
  downstream.operators.parallelism = 1
}


redis {
  database {
    duplicationstore.id = 2
    key.expiry.seconds = 3600
  }
}

redis-meta {
  database {
    userstore.id = 12
  }
}
