include "base-config.conf"

kafka {
  input.topic = ${job.env}".generate.certificate.request"
  output.failed.topic = ${job.env}".generate.certificate.failed"
  output.duplicate.topic = ${job.env}".generate.certificate.duplicate"
  output.unique.topic = ${job.env}".generate.certificate.unique"
  groupId = ${job.env}".certificate-dedup-group"
}

clickhouse {
  url = "jdbc:clickhouse://localhost:8123/warehouse?compress=0&decompress=0"
  username = "pyspark"
  password = "PySp@r712"
  batch.size = 100

  # Database tables
  table{
    certificates = "certificates"
  }}

task {
  consumer.parallelism = 4
  downstream.operators.parallelism = 1
}


redis {
  database {
    duplicationstore.id = 2
    key.expiry.seconds = 3600
  }
}

redis-meta {
  database {
    userstore.id = 12
  }
}