---
- hosts: "{{remote}}"
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
    - "{{ inventory_dir }}/group_vars/env.yml"
  become: yes
  become_user: "{{ analytics_user }}"
  roles:
   - data-products-deploy
